# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'PodTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodTest

  pod "ThinkingSDK", :path => "../../"
#  pod "ThinkingSDK/TDPushSDK", :path => "../../"

end

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod "ThinkingSDK/TDExtensionAnalytic", :path => "../../"
  pod "ThinkingSDK/TDPushSDK", :path => "../../"

  # Pods for NotificationService

end

