# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ThinkingSDKDEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!
  
  
  pod "ThinkingSDK", :path => "../"
  pod 'Masonry'
  pod 'AppsFlyerFramework'
  pod 'IronSourceSDK','7.1.8.0'
  pod 'Adjust', '~> 4.29.2'
  pod 'Branch', '~> 1.39.1'
#热云
  pod 'AnyThinkiOS'

# TradPlus
  pod 'TradPlusAdSDK', '6.9.10'
  pod 'TradPlusAdSDK/TPCrossAdapter', '6.9.10'
  pod 'TradPlusAdSDK/TPADXAdapter', '6.9.10'
  pod 'TradPlusAdSDK/BaiduAdapter', '6.9.10'
  pod 'BaiduMobAdSDK','4.83'

  
#  pod 'CocoaAsyncSocket', :inhibit_warnings => true
#  pod 'FLEX', :inhibit_warnings => true
#  pod 'MLeaksFinder', :inhibit_warnings => true
#  pod 'FBRetainCycleDetector', :inhibit_warnings => true
#  pod 'HCClangTrace', '~> 1.0.0'
  
  
  target 'ThinkingSDKDEMOTests' do
    #    pod "ThinkingSDK",:subspecs => ['Source', 'Performance', 'AppLaunch'] , :path=>"../"
    pod "ThinkingSDK", :path => "../"
    pod 'Aspects'
    pod 'YYKit', :path => "../YYKit"
    pod 'OCMock'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
