# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'ThinkingSDKDEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod "ThinkingSDK", :path => "../../"
  pod 'Masonry'
  
end
