# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

use_frameworks!

target 'ThinkingSDKDEMO' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod "ThinkingSDK", :path => "../../"
  pod 'Masonry'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
