# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'ThinkingSDKDEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod "ThinkingSDK", :path => "../../"
  pod 'Masonry'
  
  target 'NotificationCenter' do
    inherit! :search_paths
    pod "ThinkingSDK", :path => "../../"
  end

  target 'ThinkingShare' do
    inherit! :search_paths
    pod "ThinkingSDK", :path => "../../"

  end
  
  target 'ThinkingSDKDEMOTests' do
    pod "ThinkingSDK", :path => "../../"
    pod 'Aspects'
    pod 'YYKit'
    pod 'OCMock'
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
