# Uncomment the next line to define a global platform for your project
#platform :osx, '10.13'

target 'ThinkingSDKMac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThinkingSDKMac
  pod "ThinkingSDK", :path => "../../"
  pod "MJExtension"

end
