# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ThinkingSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThinkingSDK
  
  pod 'ThinkingDataCore', '1.0.0'

  target 'ThinkingSDKTests' do
    # Pods for testing
  end

end
